package dev.hive.eventcreation.controller;

import dev.hive.eventcreation.entity.EventCreation;

import org.springframework.web.bind.annotation.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Map;
import java.sql.PreparedStatement;

//Run program
//Open event request html page - http://localhost:8080/ECreation.html
//Fill out form & submit
//Intellij console displays getters effectively & errors on sql statement

@RestController
public class EventCreationController {
    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PostMapping("/api/ECreation")
    public String addEventData(@RequestBody EventCreation event) {

        System.out.println("Received event request for " + event.getTitle());

        try {

            // Check if day already has an event
            String existsSql = "SELECT COUNT(*) FROM public.event WHERE eventdate = ?";
            Integer existing = jdbcTemplate.queryForObject(existsSql, Integer.class, event.getEventDate());
            if (existing != null && existing > 0) {
                return "There is already an event on that date. Only one event per day is allowed";
            }

            KeyHolder keyHolder = new GeneratedKeyHolder();

            String eventSql = """
                        INSERT INTO public.event
                        (title, description, eventdate, eventtime, venueid)
                        VALUES (?, ?, ?, ?, ?)
                    """;

            jdbcTemplate.update(connection -> {
                PreparedStatement ps = connection.prepareStatement(eventSql, java.sql.Statement.RETURN_GENERATED_KEYS);
                ps.setString(1, event.getTitle());
                ps.setString(2, event.getDescription());
                ps.setObject(3, event.getEventDate());
                ps.setObject(4, event.getEventTime());
                ps.setInt(5, event.getVenueid());
                return ps;
            }, keyHolder);

            // Retrieve the generated keys (displayautogenerated eventid)
            Map<String, Object> keys = keyHolder.getKeys();

            if (keys == null || !keys.containsKey("eventid")) {
                throw new RuntimeException("Failed to retrieve event ID");
            }

            Integer eventId = (Integer) keys.get("eventid");

            return "Inserted successfully. EventId: " + eventId;

        } catch (Exception e) {
            e.printStackTrace();
            return "Error inserting data: " + e.getMessage();
        }
    }

    @GetMapping("/api/events")
    public List<EventCreation> getAllEvents() {
        String selectSql = """
                SELECT * FROM public.event
                """;

        return jdbcTemplate.query(selectSql, (rs, rowNum) -> {
            EventCreation event = new EventCreation();
            event.setEventid(rs.getInt("eventid"));
            event.setTitle(rs.getString("title"));
            event.setDescription(rs.getString("description"));
            event.setEventDate(rs.getObject("eventdate", LocalDate.class));
            event.setEventTime(rs.getObject("eventtime", LocalTime.class));
            event.setVenueid(rs.getInt("venueid"));
            return event;
        });
    }

    @GetMapping("/api/events/{id}")
    public EventCreation getEventById(@PathVariable int id) {
        String sql = """
                SELECT * FROM public.event WHERE eventid = ?
                """;

        try {
            return jdbcTemplate.queryForObject(sql, (rs, rowNum) -> {
                EventCreation event = new EventCreation();
                event.setEventid(rs.getInt("eventid"));
                event.setTitle(rs.getString("title"));
                event.setDescription(rs.getString("description"));
                event.setEventDate(rs.getObject("eventdate", java.time.LocalDate.class));
                event.setEventTime(rs.getObject("eventtime", java.time.LocalTime.class));
                event.setVenueid(rs.getInt("venueid"));
                return event;
            }, id);

        } catch (Exception e) {
            throw new RuntimeException("Event not found with id: " + id);
        }
    }

    @PutMapping("/api/events/{id}")
    public String updateEvent(@PathVariable int id, @RequestBody EventCreation event) {
        String sql = """
                UPDATE public.event
                SET title = ?, description = ?, eventdate = ?, eventtime = ?, venueid = ?
                WHERE eventid = ?
                """;

        int rowsAffected = jdbcTemplate.update(sql, event.getTitle(), event.getDescription(), event.getEventDate(), event.getEventTime(), event.getVenueid(), id);

        if (rowsAffected > 0) {
            return "Event updated successfully";
        } else {
            return "Update failed for id: " + id;
        }
    }
}
