package dev.hive.eventcreation.controller;

import dev.hive.eventcreation.entity.EventCreation;

import org.springframework.web.bind.annotation.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import java.util.Map;
import java.sql.PreparedStatement;

//Run program
//Open event request html page - http://localhost:8080/ECreation.html
//Fill out form & submit
//Intellij console displays getters effectively & errors on sql statement

@RestController
public class EventCreationController {
    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PostMapping("/api/ECreation")
    public String addEventData(@RequestBody EventCreation event) {

        System.out.println("Received event request for " + event.getTitle());

        try {
            KeyHolder keyHolder = new GeneratedKeyHolder();

            String eventSql = """
                        INSERT INTO public.event
                        (title, description, eventdate, eventtime, venueid)
                        VALUES (?, ?, ?, ?, ?)
                    """;

            jdbcTemplate.update(connection -> {
                PreparedStatement ps = connection.prepareStatement(eventSql, java.sql.Statement.RETURN_GENERATED_KEYS);
                ps.setString(1, event.getTitle());
                ps.setString(2, event.getDescription());
                ps.setObject(3, event.getEventDate());
                ps.setObject(4, event.getEventTime());
                ps.setInt(5, event.getVenueid());
                return ps;
            }, keyHolder);

            // Retrieve the generated keys (displayautogenerated eventid)
            Map<String, Object> keys = keyHolder.getKeys();

            if (keys == null || !keys.containsKey("eventid")) {
                throw new RuntimeException("Failed to retrieve event ID");
            }

            Integer eventId = (Integer) keys.get("eventid");

            return "Inserted successfully. EventId: " + eventId;

        } catch (Exception e) {
            e.printStackTrace();
            return "Error inserting data: " + e.getMessage();
        }
    }
}

// Attempt 1 @ fk
/*
 * String eventSql = """
 * INSERT INTO public.eventrequest
 * (eventtype, performers, expectedattendance, agerange, additionaleventdetails,
 * eventbudget, starttime, startdate)
 * VALUES (?, ?, ?, ?, ?, ?, ?, ?)
 * """;
 * 
 * int eventRows = jdbcTemplate.update(eventSql,
 * event.getEventType(),
 * event.getPerformers(),
 * event.getAttendance(),
 * event.getAges(),
 * event.getEventDetails(),
 * event.getBudget(),
 * event.getStartTime(), // Ensure correct SQL type
 * event.getStartDate() // Ensure correct SQL type
 * );
 * 
 * String contactSql = """
 * INSERT INTO public.contactinfo
 * (companyname, contactfirstname, contactlastname, phone, email,
 * besttimetobereached, links, additionalcontactnotes)
 * VALUES (?, ?, ?, ?, ?, ?, ?, ?)
 * """;
 * 
 * int contactRows = jdbcTemplate.update(contactSql,
 * event.getCompany(),
 * event.getFirstName(),
 * event.getLastName(),
 * event.getPhone(),
 * event.getEmail(),
 * event.getContactTime(),
 * event.getLinks(), // Ensure correct SQL type
 * event.getContactNotes(),
 * eventSql// Ensure correct SQL type
 * );
 * return eventRows > 0 && contactRows > 0 ? "Data inserted successfully" :
 * "Insert failed";
 */

// Testing retrieval of data with getters
/*
 * @PostMapping("/api/eventrequest")
 * public String eventData(@RequestBody EventRequest eventData) throws
 * JsonProcessingException {
 * System.out.println("Event data received: " + eventData.getEventType() + " " +
 * eventData.getPerformers() + " " +
 * eventData.getStartDate() + " " +
 * eventData.getStartTime() + " " +
 * eventData.getAttendance() + " " +
 * eventData.getAges() + " " +
 * eventData.getOtherLabel() + " " +
 * eventData.getBudget() + " " +
 * eventData.getEventDetails());
 * 
 * System.out.println("Contact data received: " + eventData.getCompany() + " " +
 * eventData.getFirstName() + " " +
 * eventData.getLastName() + " " +
 * eventData.getPhone() + " " +
 * eventData.getEmail() + " " +
 * eventData.getContactTime() + " " +
 * eventData.getLinks() + " " +
 * eventData.getContactNotes());
 * 
 * //Returns eventData = {...}
 * System.out.println(new ObjectMapper().writeValueAsString(eventData));
 * //What's returned in webpage "alert"
 * return "Handled.";
 * }
 */
